---
functional:
  - На сайте должна быть реализована возможность регистрации через почту
  - Никнейм пользователя должен содержать от 3 до 16 символов
  - Почта должна быть валидной (содержать @ и домен)
  - Пароль пользователя должен содержать от 6 до 16 символов
  - Пароль, введенный в поле Password Confirmation должен совпадать с паролем, введенным в поле Password
  - На сайте должна быть реализована возможность регистрации через аккаунт на Github
  - На сайте должна быть реализована возможность регистрации через аккаунт на Discord
  - На сайте должна быть реализована возможность авторизации через почту
  - На сайте должна быть реализована возможность авторизации через аккаунт на Github
  - На сайте должна быть реализована возможность авторизации через аккаунт на Discord
  - На сайте должна быть реализована возможность восстановить пароль через почту
  - На сайте должна быть реализована возможность выйти из аккаунта
  - Для зарегистрированных пользователей должна быть реализована возможность редактировать свое имя в профиле
  - Для зарегистрированных пользователей должна быть реализована возможность выбирать язык программирования в профиле
  - Для зарегистрированных пользователей должна быть реализована возможность настраивать звук игры в профиле
  - Для зарегистрированных пользователей должна быть реализована возможность добавлять ссылку на аккаунт на Discord в профиле
  - Для зарегистрированных пользователей должна быть реализована возможность сохранять изменения и настройки в профиле
  - Для зарегистрированных пользователей должна быть реализована возможность видеть статистику игр в профиле
  - Для зарегистрированных пользователей должна быть реализована возможность видеть информацию по завершенным играм в профиле
  - Для зарегистрированных пользователей должна быть реализована возможность видеть рейтинг пользователей (еженедельный, ежемесячный и общий)
  - Для зарегистрированных пользователей должна быть реализована возможность посматривать профили других пользователей
  - Для зарегистрированных пользователей должна быть реализована возможность видеть список задач 
  - Для зарегистрированных пользователей должна быть реализована возможность создать новую задачу 
  - Для зарегистрированных пользователей должна быть реализована возможность видеть список турниров 
  - Для зарегистрированных пользователей должна быть реализована возможность создать новый турнир 
  - Для зарегистрированных пользователей должна быть реализована возможность создать новую игру
  - Для зарегистрированных пользователей должна быть реализована возможность выбрать уровень при создании игры
  - Для зарегистрированных пользователей должна быть реализована возможность выбрать тип при создании игры
  - Для зарегистрированных пользователей должна быть реализована возможность выбрать время при создании игры
  - Для зарегистрированных пользователей должна быть реализована возможность выбрать тег при создании игры
  - Для зарегистрированных пользователей должна быть реализована возможность выбрать язык программирования в игре
  - Для зарегистрированных пользователей должна быть реализована возможность сдаться в игре
  - Для зарегистрированных пользователей должна быть реализована возможность выйти из игры
  - Для зарегистрированных пользователей должна быть реализована возможность вернуться в игру
  - Для зарегистрированных пользователей должна быть реализована возможность пригласить соперника в игру
  - Для зарегистрированных пользователей должна быть реализована возможность быть зрителем в игре
  - Для зарегистрированных пользователей должна быть реализована возможность видеть задачу
  - Для зарегистрированных пользователей должна быть реализована возможность видеть оставшееся время в поле timeout
  - Для зарегистрированных пользователей должна быть реализована возможность писать решение (код) задачи в редакторе
  - Для зарегистрированных пользователей должна быть реализована возможность сбросить написанное решение
  - Для зарегистрированных пользователей должна быть реализована возможность общаться в чате игры с соперником
  - Для зарегистрированных пользователей должна быть реализована возможность общаться в общем чате с пользователями
  - Для зарегистрированных пользователей должна быть реализована возможность посмотреть историю игры
  - Для зарегистрированных пользователей должна быть реализована возможность проверить решение
  - Для зарегистрированных пользователей должна быть реализована возможность исправлять проверенное решение
  - Для зарегистрированных пользователей должна быть реализована возможность провести повторный матч (реванш)
  - Для зарегистрированных пользователей должна быть реализована возможность видеть статус игры
  - Победитель в игре должен определяться по самому быстрому верному решению задачи
  
non-functional:
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть доступен для обновления и разработки новых функциональностей
  - Сайт должен быть прост в обслуживании и обновлении
  - Сайт должен быть способен обрабатывать большое количество трафика без снижения производительности
  - Сайт должен быть оптимизирован для скорости работы
  - Сайт должен быть доступен, когда это необходимо
  - Сайт должен быть доступен на различных устройствах и платформах
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть надежным, удобным в использовании и соответствовать требованиям пользователя
  - Сайт должен быть понятен и прост в использовании
  
implicit:
  - Незарегистрированный пользователь не может войти в аккаунт
  - Незарегистрированный пользователь не может создавать игру
  - Неавторизованный пользователь не может создавать игру
  - При вводе данных, не соответствующих условиям, должны выходить сообщения об ошибке
  - Пользователи не могут вносить изменения в статистику и рейтинги
  - Пользователь не может вносить изменения в условия задач
  - Пользователь не может писать код в редакторе (поле) соперника
  - Зрители не могут писать код во время игры
